server:
  port: 8888

spring:
  profiles:
    active: dev
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  aop:
    proxy-target-class: true
  datasource:
      # 是否开启 SQL日志输出，生产环境建议关闭，有性能损耗
    hikari:
      connection-timeout: 30000
      max-lifetime: 120000
      max-pool-size: 15
      min-idle: 5
      connection-test-query: select 1
      pool-name: CocoHikariCP
      idle-timeout: 30000
    # 配置默认数据源
    datasource:
      # 数据源-1，名称为 base
      username: root
       password: keke2012
       driver-class-name: com.mysql.cj.jdbc.Driver
       url: jdbc:mysql://123.206.87.88:3306/platform?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2b8
  redis:
    # Redis数据库索引（默认为 0）
    database: 1
    # Redis服务器地址
    host: 123.206.87.88
    # Redis服务器连接端口
    port: 6379
    # Redis 密码
    password: keke2012
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 8
        # 连接池中的最大空闲连接
        max-idle: 500
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 2000
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 10000
    # 连接超时时间（毫秒）
    timeout: 5000
mybatis-plus:
  type-aliases-package: cn.ccoco.platform.*.entity
  mapper-locations: classpath:mapper/*/*.xml,mapper/*/*/*.xml
  configuration:
    jdbc-type-for-null: null
  global-config:
    banner: false
    db-config:
      select-strategy: not_empty
logging:
  level:
    com:
      baomidou:
        mybatisplus:
          core:
            metadata:
              TableInfoHelper: error
